
#pragma once

#define MATRIX_ROWS 5
#define MATRIX_COLS 4

#define TAPPING_TERM 200


#define MOUSEKEY_INTERVAL 20
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

/* ws2812 RGB LED */
#define WS2812_DI_PIN B15

#define RGBLED_NUM 10    // Number of LEDs

// The number of LEDs connected
#define RGB_MATRIX_LED_COUNT 1

/* RGB key status */
#define RGBLIGHT_LAYERS

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE

#define WS2812_PWM_DRIVER PWMD1
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_PAL_MODE 2
#define WS2812_PWM_COMPLEMENTARY_OUTPUT
#define WS2812_DMA_STREAM STM32_DMA1_STREAM5
#define WS2812_DMA_CHANNEL 6

 
#define AUDIO_PIN A5

#ifdef AUDIO_ENABLE
#   define STARTUP_SONG    SONG(STARTUP_SOUND)
#   define GOODBYE_SONG    SONG(GOODBYE_SOUND)
#   define AUDIO_CLICKY
#define AUDIO_CLICKY_FREQ_MIN 65.0f         // Default 65
	#define AUDIO_CLICKY_FREQ_DEFAULT 400.0f    // Default 440
    #define AUDIO_CLICKY_FREQ_MAX 500.0f       // Defaul 1500
#   define AUDIO_CLICKY_FREQ_RANDOMNESS 1.0f
// #   define MIDI_BASIC
#   define MUSIC_MASK keycode != KC_NO

#define AUDIO_DAC_OFF_VALUE 0
#endif

